### ISSUE TITLE
ValueError when running demo.py and app.py

### ISSUE THREAD

**Issue by quietscientist** [OpenMotionLab/MotionGPT#23]
Hi there, I'm trying to get the demo up and running, but encounter the following error after following the provided instructions and adding any missing files. 

Global seed set to 1234
Traceback (most recent call last):
  File "/home/msegado/MotionGPT/app.py", line 31, in <module>
    datamodule = build_data(cfg, phase="test")
  File "/home/msegado/MotionGPT/mGPT/data/build_data.py", line 10, in build_data
    return instantiate_from_config(data_config)
  File "/home/msegado/MotionGPT/mGPT/config.py", line 42, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/msegado/MotionGPT/mGPT/data/HumanML3D.py", line 76, in __init__
    self._sample_set = self.get_sample_set(overrides={"split": "test", "tiny": True})
  File "/home/msegado/MotionGPT/mGPT/data/__init__.py", line 20, in get_sample_set
    return self.DatasetEval(**sample_params)
  File "/home/msegado/MotionGPT/mGPT/data/humanml/dataset_t2m_eval.py", line 24, in __init__
    super().__init__(data_root, split, mean, std, max_motion_length,
  File "/home/msegado/MotionGPT/mGPT/data/humanml/dataset_t2m.py", line 152, in __init__
    name_list, length_list = zip(
ValueError: not enough values to unpack (expected 2, got 0)

I get the same error when running  both "python demo.py --cfg ./configs/config_h3d_stage3.yaml --example ./demos/t2m.txt" and "python app.py"

Any suggestions? Thanks!

**Comment by quietscientist** [comment]
Solved: Solution was to unzip "texts.zip" in datasets/humanml3d
