### ISSUE TITLE
gradio app has error: "ValueError: Need to enable queue to use generator."

### ISSUE THREAD

**Issue by hdjsjyl** [OpenMotionLab/MotionGPT#38]
Hi Author,
    While running app.py, I input prompt, get the following error.
Any suggestion is appreciated. Thanks

Traceback (most recent call last):
  File "/opt/conda/envs/mgpt/lib/python3.10/site-packages/gradio/routes.py", line 508, in predict
    output = await route_utils.call_process_api(
  File "/opt/conda/envs/mgpt/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/mgpt/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/opt/conda/envs/mgpt/lib/python3.10/site-packages/gradio/blocks.py", line 1117, in call_function
    raise ValueError("Need to enable queue to use generators.")
ValueError: Need to enable queue to use generators.

**Comment by billl-jiang** [comment]
Hi, @hdjsjyl 

This error is caused by the discrepancy between running [gradio](https://www.gradio.app/) on Huggingface spaces and running it locally. To address this, we have made updates to ensure it is compatible with running the web UI demo locally.

**Comment by hdjsjyl** [comment]
hi @billl-jiang ,
    Thanks for your reply. I pull the changes and get the following error:

AttributeError: Missing attribute "w_vectorizer"

Thanks

**Comment by billl-jiang** [comment]
The updates were previously stalled due to a network connection issue. Please try pulling from GitHub again.

**Comment by hdjsjyl** [comment]
HI @billl-jiang ,
    It works now. Thanks for your help.
The following is the result I got.
<img width="567" alt="image" src="https://github.com/OpenMotionLab/MotionGPT/assets/7590139/9fefd699-4442-49a6-a744-09afc2e04b22">


But it is different from the result of huggingface demo.
Is there any way of getting the same results as huggingface demol for 3D avatar rendering? Thanks

**Comment by kruzel** [comment]
I just cloned code from huggingface and have same error,
where can I find the fix?

![image](https://github.com/OpenMotionLab/MotionGPT/assets/975963/c39e7343-7902-4d0a-81a2-c95cf03c2aa3)

**Comment by shileims** [comment]
The author has update the code in Github. You can try pull the latest code in github and try demo. The issue you mentioned has been solved. But will show results I mentioned above. @kruzel

**Comment by kruzel** [comment]
code on github require the dataset,
