### ISSUE TITLE
Help me run python app.py 

### ISSUE THREAD

**Issue by huijunam** [OpenMotionLab/MotionGPT#51]
Hi, I am running the gradio demo using python app.py. now I am encountering this error. 
please help me how to fix. 

Global seed set to 1234
Traceback (most recent call last):
  File "/Users/namhuiju/opt/anaconda3/envs/mgpt/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/Users/namhuiju/opt/anaconda3/envs/mgpt/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/deps/whisper-large-v2/resolve/main/preprocessor_config.json

**Comment by HIT-ZY** [comment]
How to solve this problem?

**Comment by 10FCPRO** [comment]
most probably u need to modify the path to the correct whisper large path

**Comment by ChoYongchae** [comment]
change whisper path at `configs/assets.yaml:L26`
```
# (from)
# whisper_path: deps/whisper-large-v2 # path for whisper model, webui only
# (to)
  whisper_path: **openai**/whisper-large-v2 # path for whisper model, webui only
```
(maybe author already downloaded whisper-large-v2 at `deps` directory)
