### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by marybloodyzz** [OpenMotionLab/MotionGPT#53]
Hi, I got this issue even after unzip the texts.zip file. 
Traceback (most recent call last):
  File "/home/zzmarybloody/MotionGPT/demo.py", line 237, in <module>
    main()
  File "/home/zzmarybloody/MotionGPT/demo.py", line 147, in main
    datamodule = build_data(cfg)
  File "/home/zzmarybloody/MotionGPT/mGPT/data/build_data.py", line 10, in build_data
    return instantiate_from_config(data_config)
  File "/home/zzmarybloody/MotionGPT/mGPT/config.py", line 42, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/zzmarybloody/MotionGPT/mGPT/data/HumanML3D.py", line 76, in __init__
    self._sample_set = self.get_sample_set(overrides={"split": "test", "tiny": True})
  File "/home/zzmarybloody/MotionGPT/mGPT/data/__init__.py", line 20, in get_sample_set
    return self.DatasetEval(**sample_params)
  File "/home/zzmarybloody/MotionGPT/mGPT/data/humanml/dataset_t2m_eval.py", line 24, in __init__
    super().__init__(data_root, split, mean, std, max_motion_length,
  File "/home/zzmarybloody/MotionGPT/mGPT/data/humanml/dataset_t2m.py", line 165, in __init__
    name_list, length_list = zip(
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by QvQKing** [comment]
Me too! I also want to know how to solve it!

**Comment by santurini** [comment]
same problem

**Comment by lzhyu** [comment]
I fixed it by unzipping the `texts.zip` in `datasets/humanml3d/`.

**Comment by santurini** [comment]
I was able to solve this problem but now I have problems in building the model. Do you have shape mismatch when loading the pretrained mGPT?

**Comment by billl-jiang** [comment]
The issue you're encountering is most likely related to missing data. By default, we save all data into a single temporary data file for faster I/O operations. You can try resolving it by deleting the "tmp" folder within your dataset folder and then attempting the operation again.

**Comment by santurini** [comment]
@billl-jiang Yes, I was able to solve this issue, but now I have a shape mismatch in the model parameters when loading the state dict.

**Comment by santurini** [comment]
@Yawningx first of all you need to download the HumanML3D dataset and place it in `./datasets`. Then, inside the HumanML3D folder you just have to unzip the `texts.zip` file.

For me it worked, while for the second problem there is row 77 in`mGPT.data.HumanML3D.HumanML3DDataModule` that changes incorrectly the cfg.DATASET.NFEATURES, so I just hard-coded it to 263.

**Comment by Yawningx** [comment]
> @Yawningx I asked the authors of HumanML3D for the zipped dataset and then unzipped `texts.zip`.
> 
> For me it worked, while for the second problem there is row 77 in`mGPT.data.HumanML3D.HumanML3DDataModule` that changes incorrectly the cfg.DATASET.NFEATURES, so I just hard-coded it to 263.

Thanks for your reply! But the error still exist, my HumanML3D folder has structure as follows:
![1701953381452](https://github.com/OpenMotionLab/MotionGPT/assets/74655243/1aa7c06b-a0e3-4f8e-a444-21b55cf6676a)
First I unzip the texts.zip, then I put the instructions data in `prepare/instructions` to the same folder of HumanML3D dataset, as it said in README.md.
Did I miss sth important?

**Comment by GoBigxs** [comment]
> I was able to solve this problem but now I have problems in building the model. Do you have shape mismatch when loading the pretrained mGPT?

Hi @santurini how did you solve it? I met the same issue.

**Comment by lixiang927047** [comment]
> > @Yawningx I asked the authors of HumanML3D for the zipped dataset and then unzipped `texts.zip`.
> > For me it worked, while for the second problem there is row 77 in`mGPT.data.HumanML3D.HumanML3DDataModule` that changes incorrectly the cfg.DATASET.NFEATURES, so I just hard-coded it to 263.
> 
> Thanks for your reply! But the error still exist, my HumanML3D folder has structure as follows: ![1701953381452](https://private-user-images.githubusercontent.com/74655243/288762312-1aa7c06b-a0e3-4f8e-a444-21b55cf6676a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDg2MzYsIm5iZiI6MTcwNjE0ODMzNiwicGF0aCI6Ii83NDY1NTI0My8yODg3NjIzMTItMWFhN2MwNmItYTBlMy00ZjhlLWE0NDQtMjFiNTVjZjY2NzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAyMDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMjM4ZmUyMDc0OTllMjc2ZDkyY2NmMzcxOTZkM2JjNjJhYjFiNzFlNTc0NTMyZTU1MDJjYTk0OTNjOGE0OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kvggtDaPSQXwWH5SMRp6YUmonirSuWKgxqLqyc5O2Z8) First I unzip the texts.zip, then I put the instructions data in `prepare/instructions` to the same folder of HumanML3D dataset, as it said in README.md. Did I miss sth important?

try` cp -r prepare/instructions datasets/HumanML3D  `

**Comment by WILLOSCAR** [comment]
> > @billl-jiang Yes, I was able to solve this issue, but now I have a shape mismatch in the model parameters when loading the state dict.
> 
> Hi, could you tell me how you solved the problem? thx 😊

I'm also having this problem, are you using git clone https://github.com/EricGuo5513/HumanML3D.git directly and then unzipping the texts.zip?

**Comment by WILLOSCAR** [comment]
> @Yawningx I asked the authors of HumanML3D for the zipped dataset and then unzipped `texts.zip`.
> 
> For me it worked, while for the second problem there is row 77 in`mGPT.data.HumanML3D.HumanML3DDataModule` that changes incorrectly the cfg.DATASET.NFEATURES, so I just hard-coded it to 263.

Could you please provide me with details on what the complete dataset catalog should include? Additionally, I would like to know the amount of data contained in the "new_joints" folder. If you still have a copy of the compressed dataset, I would greatly appreciate it if you could share it with me. Thank you!

**Comment by Maxin-C** [comment]
> who can provide a right way

I met the same problem today. With the help of the comments below this issue, it was solved through the following steps:

1. Download dataset from  https://github.com/EricGuo5513/HumanML3D. KIT-ML dataset is enough for this project.
2. Make folder `datasets` under the main folder and extract the `zip` file in the `dataset`. Named the folder `humanml3d`.
3. Unrar `texts.rar`, `new_joints.rar` and `new_joint_vecs.rar` in the `datasets/humanml3d`.
4. `cp -r prepare/instructions datasets/HumanML3D` (I don't know whether it works. Just do it.) 

After finishing all steps, run `python demo.py --cfg ./configs/config_h3d_stage3.yaml --example ./demos/t2m.txt`. ValueError was solved and there are other errors displayed.

I hope my experience will help you.

<img width="202" alt="Image" src="https://github.com/user-attachments/assets/2fcf1b60-c737-4977-8d80-8453fbbe187a" />

**Comment by Maxin-C** [comment]
> > who can provide a right way
> 
> I met the same problem today. With the help of the comments below this issue, it was solved through the following steps:
> 
> 1. Download dataset from  https://github.com/EricGuo5513/HumanML3D. KIT-ML dataset is enough for this project.
> 2. Make folder `datasets` under the main folder and extract the `zip` file in the `dataset`. Named the folder `humanml3d`.
> 3. Unrar `texts.rar`, `new_joints.rar` and `new_joint_vecs.rar` in the `datasets/humanml3d`.
> 4. `cp -r prepare/instructions datasets/HumanML3D` (I don't know whether it works. Just do it.)
> 
> After finishing all steps, run `python demo.py --cfg ./configs/config_h3d_stage3.yaml --example ./demos/t2m.txt`. ValueError was solved and there are other errors displayed.
> 
> I hope my experience will help you.
> 
> <img alt="Image" width="202" src="https://private-user-images.githubusercontent.com/57470650/423421486-2fcf1b60-c737-4977-8d80-8453fbbe187a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIyODI5ODMsIm5iZiI6MTc0MjI4MjY4MywicGF0aCI6Ii81NzQ3MDY1MC80MjM0MjE0ODYtMmZjZjFiNjAtYzczNy00OTc3LThkODAtODQ1M2ZiYmUxODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzE4VDA3MjQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNWNmNzQ2ZTk4MWRlZjhjOTI1Njk4MWQwNTQ0NWJkYTY3MWUzYzcxYjliMDNhYzBhNjkxYjQ4MmMyNzE0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5FGnSTORpXwnncEwg78AYKBtE_uCss_SDPD0S6r6wBo">

After performing the above steps, the bug I encountered is:

```
RuntimeError: Error(s) in loading state_dict for MovementConvEncoder:
size mismatch for main.0.weight: copying a param with shape torch.Size([512, 259, 4]) from checkpoint, the shape in current model is torch.Size([512, 247, 4]).
```

This bug is also mentioned in #62. By referring to the experience in #62, I realized that the suggestion I provided here was incorrect. This project requires the use of the AMASS version of the dataset, not the KIT-ML dataset.

Therefore, in the dataset import section of the above steps, you should not directly download the KIT-ML version of the dataset. Instead, you need to refer to the instructions in [HumanML3D](https://github.com/EricGuo5513/HumanML3D.git) to locally build the AMASS version of the dataset. The other steps remain the same, otherwise, you will encounter the issues mentioned in #62. If you can read Chinese blogs, you can also refer to https://blog.csdn.net/qq_53930200/article/details/137646272?spm=1001.2014.3001.5501 (I implemented it by following this blog).

Currently, my code runs successfully, and I hope my advice can help you.

Tips: It's worth noting that there are some minor bugs in the raw_pose_processing.ipynb file of HumanML3D, but they are not difficult to fix. Don't just click run and leave it unattended.
