### ISSUE TITLE
TypeError: Audio.__init__() got an unexpected keyword argument 'source'

### ISSUE THREAD

**Issue by QvQKing** [OpenMotionLab/MotionGPT#54]
Traceback (most recent call last):
  File "/root/autodl-tmp/MotionGPT-main/app.py", line 512, in <module>
    aud = gr.Audio(source="microphone",
  File "/root/miniconda3/envs/mgpt/lib/python3.10/site-packages/gradio/component_meta.py", line 146, in wrapper
    return fn(self, **kwargs)
TypeError: Audio.__init__() got an unexpected keyword argument 'source'
Hello, I want to know how to solve this problem. Thanks!

**Comment by tshrjn** [comment]
Gradio had a recent major upgrade, that's probably why it has some changes in api.

Try downgrading the gradio library:
`pip install gradio==3.41.0`

**Comment by FishWoWater** [comment]
For me (2023.12.23) 
Erorr still occurs with `gradio == 3.41.0`: 
`TypeError: Audio.__init__() got an unexpected keyword argument 'source'`

`pip install gradio==3.41.0` is ok

**Comment by Gelercatty** [comment]
i tried but another error exist, so i tried gradio == 3.44.0 is  ok， perfect solved
