### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by meongeun** [OpenMotionLab/MotionGPT#85]
An issue arises in the code at line 3284 of modeling_utils.py, specifically with the following snippet: 

```
with safe_open(resolved_archive_file, framework="pt") as f
```

Have you encountered this error before, and do you have any insights into its cause?

**Comment by devin12422** [comment]
I'm getting the same error, quick google search say's it's an issue with the archive the weights are stored in.

**Comment by Liuhm0710** [comment]
Traceback (most recent call last):
  File "/./diffumask/myenv/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 102, in load_state_dict
    return safetensors.torch.load_file(checkpoint_file, device="cpu")
  File "/./diffumask/myenv/lib/python3.8/site-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

facing the same problem too

**Comment by quietscientist** [comment]
Hi there, this fix doesn't seem to work in this case. I checked that the file sizes are the same for motiongpt_s3_h3d.tar, and am still getting this error when trying to train the vae (stage 1)

**Comment by cartucho-move** [comment]
`sudo apt-get install git-lfs` may also be needed if on Ubuntu
